version: "3.2"
services:
  cdk:
    image: ghcr.io/adamsnimbus/aws-cdk-v2:2.3.0
    userns_mode: host
    user: node
    working_dir: /opt/app
    volumes:
    - ~/.aws:/root/.aws
    - .:/opt/app:rw
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
      - CDK_DEFAULT_ACCOUNT
      - CDK_DEFAULT_REGION
